### ISSUE TITLE
Question - Why expose port 80?

### ISSUE THREAD

**Issue by codyburleson** [jontutcher/stardog-docker#1]
If Stardog is on 5820, why are you exposing port 80 in the Docker file? Is there some sort of Stardog SPARQL endpoint or service or something on port 80 that I'm just not aware of? Or is that for some other use that you have of this container, but not specifically needed for Stardog?

**Comment by jontutcher** [comment]
@codyburleson Thanks - you're right! Just tweaked accordingly :)
